FROM oraclelinux:8-slim

LABEL version="20.3.2.1"
LABEL description="TOTVS DBAccess" 
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

ENV LICENSE_TCP_PORT=2234
ENV LICENSE_CONSOLEFILE=/totvs/licenseserver/bin/appserver/licenseserver.log
ENV LICENSE_PORT=5555
ENV LICENSE_WEBAPP_PORT=8020

COPY ./totvs /totvs

RUN chmod +x /totvs/entrypoint.sh

ENTRYPOINT [ "/totvs/entrypoint.sh" ]

EXPOSE 2234 5555 8020