FROM oraclelinux:8-slim

ENV LICENSE_TCP_PORT=2234
ENV LICENSE_CONSOLEFILE=/totvs/licenseserver/bin/appserver/licenseserver.log
ENV LICENSE_PORT=5555
ENV LICENSE_WEBAPP_PORT=8020

COPY ./totvs /totvs

RUN chmod +x /totvs/entrypoint.sh

ENTRYPOINT [ "/totvs/entrypoint.sh" ]

EXPOSE 2234 5555 8020