FROM oraclelinux:8

COPY . /

RUN mv /totvs/resources/etc/* /etc/ \
    && mv /totvs/resources/opt/* /opt/ \
    && chmod +x /totvs/entrypoint.sh \
    && dnf update -y \
    && dnf install nano unixODBC-devel

ENTRYPOINT [ "/totvs/entrypoint.sh" ]

EXPOSE 7890 7891