FROM oraclelinux:8-slim

ENV DATABASE_PASSWORD=MicrosoftSQL2019
ENV DBACCESS_LICENSE_SERVER=totvs_licenseserver
ENV DBACCESS_LICENSE_PORT=5555
ENV DBACCESS_CONSOLEFILE=/totvs/dbaccess/multi/dbconsole.log

COPY ./totvs /totvs

RUN cp /totvs/resources/etc/* /etc/ \
    && cp -r /totvs/resources/opt/* /opt/ \
    && chmod +x /totvs/entrypoint.sh \
    && microdnf install nano unixODBC-devel

ENTRYPOINT [ "/totvs/entrypoint.sh" ]

EXPOSE 7890 7891