FROM oraclelinux:8-slim

COPY . /

RUN mv /totvs/resources/etc/* /etc/ \
    && mv /totvs/resources/opt/* /opt/ \
    && chmod +x /totvs/entrypoint.sh \
    && microdnf install nano unixODBC-devel

ENTRYPOINT [ "/totvs/entrypoint.sh" ]

EXPOSE 7890 7891