FROM oraclelinux:8-slim

LABEL release="12.1.2410"
LABEL build="24.3.0.1"
LABEL dbapi="24.1.0.0"
LABEL description="TOTVS Aplication Server Protheus (REST)" 
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

ENV APPSERVER_RPO_CUSTOM="/totvs/protheus/apo/custom.rpo"
ENV APPSERVER_DBACCESS_DATABASE=MSSQL
ENV APPSERVER_DBACCESS_SERVER=totvs_dbaccess
ENV APPSERVER_DBACCESS_PORT=7890
ENV APPSERVER_DBACCESS_ALIAS=protheus
ENV APPSERVER_CONSOLEFILE="/totvs/protheus/bin/appserver/appserver.log"
ENV APPSERVER_MULTIPROTOCOLPORTSECURE=0
ENV APPSERVER_MULTIPROTOCOLPORT=1
ENV APPSERVER_LICENSE_SERVER=totvs_licenseserver
ENV APPSERVER_LICENSE_PORT=5555
ENV APPSERVER_PORT=1235
ENV APPSERVER_WEB_PORT=12355
ENV APPSERVER_REST_PORT=8080
ENV APPSERVER_WEB_MANAGER=8088

COPY ./totvs /totvs

RUN chmod +x /totvs/entrypoint.sh \
    && chmod +x /totvs/appserver.sh \
    && microdnf update -y \
    && microdnf install procps-ng \
    && microdnf install python3 \
    && pip3 install flask

ENTRYPOINT [ "/totvs/entrypoint.sh" ]

EXPOSE 1235 12355 8080 8088